//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compilers\parsers\antlr\BasicIntAST\grammar\basicintast\parser\Basic.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {

package basicintast.parser;
import basicintast.util.*;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BasicParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBasicListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>programStmt</c>
	/// labeled alternative in <see cref="BasicParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgramStmt([NotNull] BasicParser.ProgramStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>programStmt</c>
	/// labeled alternative in <see cref="BasicParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgramStmt([NotNull] BasicParser.ProgramStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtPrint</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtPrint([NotNull] BasicParser.StmtPrintContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtPrint</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtPrint([NotNull] BasicParser.StmtPrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtRead</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtRead([NotNull] BasicParser.StmtReadContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtRead</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtRead([NotNull] BasicParser.StmtReadContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtAttr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtAttr([NotNull] BasicParser.StmtAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtAttr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtAttr([NotNull] BasicParser.StmtAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtExpr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtExpr([NotNull] BasicParser.StmtExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtExpr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtExpr([NotNull] BasicParser.StmtExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtCond</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtCond([NotNull] BasicParser.StmtCondContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtCond</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtCond([NotNull] BasicParser.StmtCondContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] BasicParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] BasicParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifElseStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseStmt([NotNull] BasicParser.IfElseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifElseStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseStmt([NotNull] BasicParser.IfElseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condExpresion</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondExpresion([NotNull] BasicParser.CondExpresionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condExpresion</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondExpresion([NotNull] BasicParser.CondExpresionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condRelOp</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondRelOp([NotNull] BasicParser.CondRelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condRelOp</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondRelOp([NotNull] BasicParser.CondRelOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="BasicParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] BasicParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="BasicParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] BasicParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>printStr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStr([NotNull] BasicParser.PrintStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>printStr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStr([NotNull] BasicParser.PrintStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>printExpr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintExpr([NotNull] BasicParser.PrintExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>printExpr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintExpr([NotNull] BasicParser.PrintExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>readVar</c>
	/// labeled alternative in <see cref="BasicParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadVar([NotNull] BasicParser.ReadVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>readVar</c>
	/// labeled alternative in <see cref="BasicParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadVar([NotNull] BasicParser.ReadVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>attrExpr</c>
	/// labeled alternative in <see cref="BasicParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrExpr([NotNull] BasicParser.AttrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>attrExpr</c>
	/// labeled alternative in <see cref="BasicParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrExpr([NotNull] BasicParser.AttrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprPlus([NotNull] BasicParser.ExprPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprPlus([NotNull] BasicParser.ExprPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprMinus([NotNull] BasicParser.ExprMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprMinus([NotNull] BasicParser.ExprMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr1Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr1Empty([NotNull] BasicParser.Expr1EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr1Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr1Empty([NotNull] BasicParser.Expr1EmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr1Mult</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr1Mult([NotNull] BasicParser.Expr1MultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr1Mult</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr1Mult([NotNull] BasicParser.Expr1MultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr1Div</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr1Div([NotNull] BasicParser.Expr1DivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr1Div</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr1Div([NotNull] BasicParser.Expr1DivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr2Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr2Empty([NotNull] BasicParser.Expr2EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr2Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr2Empty([NotNull] BasicParser.Expr2EmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr2Par</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr2Par([NotNull] BasicParser.Expr2ParContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr2Par</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr2Par([NotNull] BasicParser.Expr2ParContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr2Num</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr2Num([NotNull] BasicParser.Expr2NumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr2Num</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr2Num([NotNull] BasicParser.Expr2NumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expr2Var</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr2Var([NotNull] BasicParser.Expr2VarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expr2Var</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr2Var([NotNull] BasicParser.Expr2VarContext context);
}
} // namespace Grammar
