//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compilers\parsers\antlr\BasicIntAST\grammar\basicintast\parser\Basic.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {

package basicintast.parser;
import basicintast.util.*;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BasicParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBasicVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>programStmt</c>
	/// labeled alternative in <see cref="BasicParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramStmt([NotNull] BasicParser.ProgramStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtPrint</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtPrint([NotNull] BasicParser.StmtPrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtRead</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtRead([NotNull] BasicParser.StmtReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtAttr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtAttr([NotNull] BasicParser.StmtAttrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtExpr</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtExpr([NotNull] BasicParser.StmtExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtCond</c>
	/// labeled alternative in <see cref="BasicParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtCond([NotNull] BasicParser.StmtCondContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] BasicParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifElseStmt</c>
	/// labeled alternative in <see cref="BasicParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseStmt([NotNull] BasicParser.IfElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>condExpresion</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondExpresion([NotNull] BasicParser.CondExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>condRelOp</c>
	/// labeled alternative in <see cref="BasicParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondRelOp([NotNull] BasicParser.CondRelOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="BasicParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] BasicParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printStr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStr([NotNull] BasicParser.PrintStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printExpr</c>
	/// labeled alternative in <see cref="BasicParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpr([NotNull] BasicParser.PrintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readVar</c>
	/// labeled alternative in <see cref="BasicParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadVar([NotNull] BasicParser.ReadVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>attrExpr</c>
	/// labeled alternative in <see cref="BasicParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrExpr([NotNull] BasicParser.AttrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprPlus([NotNull] BasicParser.ExprPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprMinus([NotNull] BasicParser.ExprMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Empty([NotNull] BasicParser.Expr1EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Mult</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Mult([NotNull] BasicParser.Expr1MultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Div</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Div([NotNull] BasicParser.Expr1DivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Empty</c>
	/// labeled alternative in <see cref="BasicParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Empty([NotNull] BasicParser.Expr2EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Par</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Par([NotNull] BasicParser.Expr2ParContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Num</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Num([NotNull] BasicParser.Expr2NumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Var</c>
	/// labeled alternative in <see cref="BasicParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Var([NotNull] BasicParser.Expr2VarContext context);
}
} // namespace Grammar
